services:
  randomwordbot:
    container_name: randomwordbot
    image: git.postfmly.com/admin/randomwordbot:arm64
    restart: unless-stopped
    ports:
      - "8003:8003"
    volumes:
      - db:/app/db
    environment:
      - LOGO_NAME=randomwordbot.webp
      - LOGO_PATH=./utils/images
      - LOGO_PORT=8003
      - LOGO_URL=https://randomwordbot.postfmly.us/randomwordbot.webp
      - TZ=America/Chicago
    env_file: .env
    labels:
      - wud.display.name=RandomWordBot
      - homepage.group=Personal
      - homepage.name=RandomWordBot
      - homepage.icon=https://randomwordbot.postfmly.com/randomwordbot.webp

volumes:
  db:

networks: {}
